[package]
name = "recipes"
version = "0.1.0"
authors = ["Jeremy Wall <jeremy@marzhillstudios.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abortable_parser = "~0.2.5"
chrono = "~0.4"

[dependencies.uuid]
version = "~0.8.2"
features = ["v4"]

[dependencies.num-rational]
version = "~0.4.0"