[package]
name = "recipes"
version = "0.2.14"
authors = ["Jeremy Wall <jeremy@marzhillstudios.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abortable_parser = "~0.2.6"
chrono = "~0.4"
serde = "1.0.144"

[dependencies.num-rational]
version = "~0.4.0"

[dependencies.Inflector]
version = "0.11.4"
