[package]
name = "kitchen"
version = "0.2.0"
authors = ["Jeremy Wall <jeremy@marzhillstudios.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
recipes = {path = "../recipes" }
csv = "1.1.1"
warp = "0.3.2"
static_dir = "0.2.0"

[dependencies.clap]
version = "2.33.4"

[dependencies.async-std]
version = "1.10.0"
features = ["tokio1"]