[package]
name = "kitchen"
version = "0.1.0"
authors = ["Jeremy Wall <jeremy@marzhillstudios.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
recipes = {path = "../recipes" }
recipe-store = {path = "../recipe-store" }
rustyline = "~8.0.0"
