[package]
name = "kitchen"
version = "0.1.0"
authors = ["Jeremy Wall <jeremy@marzhillstudios.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
recipes = {path = "../recipes" }
csv = "1.1.1"
async-std = "1.10.0"

[dependencies.clap]
version = "2.33.4"

[dependencies.dioxus]
version = "0.1.7"
features = [ "ssr" ]