[package]
name = "kitchen-wasm"
version = "0.2.2"
edition = "2021"

[features]
ssr = []
web = []
default = ["web"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
recipes = {path = "../recipes" }
reqwasm = "0.4.0"
# This makes debugging panics more tractable.
console_error_panic_hook = "0.1.7"
sycamore-router = "0.7.1"
serde_json = "1.0.79"

[dependencies.wasm-bindgen]
version = "=0.2.78"

[dependencies.web-sys]
version = "0.3"
features = [ "Storage", "Window" ]

[dependencies.sycamore]
version = "0.7.1"
features = ["futures", "serde", "default"]