[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
recipes = {path = "../recipes" }
reqwasm = "0.4.0"

[dependencies.wasm-bindgen]
version = "0.2.79"
#features = [ "console" ]

[dependencies.sycamore]
version = "0.7.1"
features = ["futures", "serde", "default"]